version: "3.9"

services:
    pgdb:
        image: postgres:14.5
        container_name: pgdb
        env_file: .env
        expose:
            - 5432
        volumes:
            - ./data:/var/lib/postgresql/data

    django:
        build:
            context: django_app
            dockerfile: Dockerfile
        container_name: django
        command: /bin/bash -c "exec invoke run-local"
        volumes:
            - ./django_app:/usr/src/app
        expose:
            - 8000
        depends_on:
            - pgdb
        env_file: .env

    react:
        image: node:16.17
        container_name: react
        volumes:
            - ./frontend:/frontend
        working_dir: /frontend
        command: bash -c "npm install && npm start"

    nginx:
        image: nginx:1.23.0
        container_name: nginx
        volumes:
            - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
            - ./django_app/static:/static
        expose:
            - 8000
            - 3000
        ports:
            - "8000:8000"
            - "3000:3000"
        depends_on:
            - django