version: "3.9"
services:
  pgdb:
    image: postgres:14.5
    container_name: pgdb
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  django:
      build:
          context: django_app
          dockerfile: Dockerfile
      container_name: django
      command: /bin/bash -c "exec invoke test"
      volumes:
          - ./django_app:/usr/src/app
      ports:
          - "8000:8000"
      expose:
          -   8000
      depends_on:
          - pgdb
      env_file: .env