# Generated by Django 4.1.1 on 2022-11-02 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expenses_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-date_time'], 'verbose_name': 'Expenses'},
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='date',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='time',
        ),
        migrations.AddField(
            model_name='expenses',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date time'),
        ),
    ]
