# Generated by Django 4.1.1 on 2022-11-02 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expenses_options_remove_expenses_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Expenses'},
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='date_time',
        ),
        migrations.AddField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 2), verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='time',
            field=models.TimeField(default=datetime.time(22, 48, 26, 974153), verbose_name='Time'),
        ),
    ]
