# Generated by Django 4.1.1 on 2022-11-02 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_expenses_options_remove_expenses_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='time',
            field=models.TimeField(default=datetime.time(22, 53, 53, 262476), verbose_name='Time'),
        ),
    ]
