# Generated by Django 4.1.1 on 2022-11-02 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_expenses_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='time',
            field=models.TimeField(default=datetime.time(23, 0, 26, 236319), verbose_name='Time'),
        ),
    ]
