# Generated by Django 4.1.1 on 2022-11-03 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_expenses_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 3), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='time',
            field=models.TimeField(default=datetime.time(6, 43, 22, 953407), verbose_name='Time'),
        ),
    ]
