# Generated by Django 4.1.1 on 2022-11-03 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_expenses_date_alter_expenses_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='time',
            field=models.TimeField(default=datetime.time(6, 46, 30, 283096), verbose_name='Time'),
        ),
    ]
