# Generated by Django 4.1.1 on 2022-11-03 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_alter_expenses_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='time',
            field=models.TimeField(default=datetime.time(7, 22, 19, 630674), verbose_name='Time'),
        ),
    ]
