# Generated by Django 4.1.1 on 2022-11-03 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_alter_expenses_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='time',
            field=models.TimeField(default=datetime.time(7, 23, 1, 725294), verbose_name='Time'),
        ),
    ]
