# Generated by Django 4.1.1 on 2022-11-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_alter_expenses_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='time',
            field=models.TimeField(default='07:57', verbose_name='Time'),
        ),
    ]
