# Generated by Django 4.1.1 on 2022-11-03 20:37

from django.db import migrations, models
import expenses.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_alter_expenses_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=expenses.models.get_now_date, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='time',
            field=models.TimeField(default=expenses.models.get_now_time, verbose_name='Time'),
        ),
    ]
