# Generated by Django 4.1.1 on 2023-04-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_alter_expenses_date_alter_expenses_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='limit',
            field=models.BooleanField(default=True),
        ),
    ]
