# Generated by Django 4.1.1 on 2023-04-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021_remove_expenses_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='limit',
            field=models.BooleanField(default=True),
        ),
    ]
