# Generated by Django 4.1.1 on 2023-04-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0022_expenses_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='limit',
        ),
    ]
